model_params:
  name: 'NumeraiVAE'
  in_channels: 1191
  latent_dim: 32


data_params:
  data_path: "./../numerai/train.parquet"
  train_batch_size: 4096
  val_batch_size:  4096
  num_workers: 8


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 5000

logging_params:
  save_dir: "logs/"
  name: "NumeraiVAE"
